image: docker:latest
services:
  - docker:dind
stages:
  - build
  - push
build:
  stage: build
  script:
    - echo 'Building docker image...'
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker images
push:
  stage: push
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
