# Using r-base image
FROM r-base:{{R_VERSION}}

# Setting environment variables

ENV {{R_ENV_KEY}}={{R_ENV_VAL}}

# Listing R packages to be installed
RUN R -e "install.packages(c({{R_PACKAGES}}), repos='http://cran.rstudio.com/')"

# working directory inside the container
WORKDIR /app

# Copying application files into the container
COPY . /app

# Exposing port
EXPOSE {{R_PORT}}

# Initializing command to run an R script or application
CMD R -e  "{{R_START_SCRIPT}}"
